src/app/color/color.component.html, src/app/color/color.component.less, src/main.less
Added behr popup in color page
=> Added behr popup in color page

src/app/door-size/door-size.component.html
added enter naviagtion and popup close
=> added enter naviagtion and popup close

src/app/lock/lock.component.html
=> html changes

src/app/hardware/hardware.component.html, src/app/hardware/hardware.component.less
=> Hardware page css changes

src/app/construction/construction.component.html, src/app/construction/construction.component.less, src/main.less
Added upshell popup class changes
=> Added upshell popup class changes

src/app/shared/english.ts, src/app/zip-results/zip-results.component.html, src/app/zip-results/zip-results.component.ts
added localisation for zip results
=> added localisation

src/app/category/category.component.html, src/app/category/category.component.ts, src/app/shared/english.ts
added localisation for category and service and repair popup
=> added localisation for category

src/app/door-size/door-size.component.html, src/app/door-size/door-size.component.ts, src/app/shared/english.ts
added localisation to door size
=> added localisation to door size

src/app/door-configuration/door-configuration.component.html, src/app/door-configuration/door-configuration.component.less
=> added doorConfiguration less

src/app/door-configuration/door-configuration.component.html
=> added popup close function

src/app/additional-options/additional-options.component.html
=> added images

src/app/door-configuration/door-configuration.component.html
=> added share click popup

src/app/category/category.component.html
=> added gdo popup classes

src/app/door-configuration/door-configuration.component.html, src/app/door-configuration/door-configuration.component.less
added gdo related screens flow design's
=> added gdo related screens

src/app/additional-options/additional-options.component.html
added additional option info image
=> added additional option info image

src/app/glass-type/glass-type.component.html, src/app/glass-type/glass-type.component.less
=> added subheader

src/app/header/header.component.html, src/main.less
added shopping cart popup design changes
=> shopping cart popup design changes

src/app/category/category.component.html, src/app/category/category.component.less, src/main.less
added banner image in category
=> added banner image in category

src/app/category/category.component.html, src/app/category/category.component.less
=> added banner image css

src/app/door-configuration/door-configuration.component.html, src/main.less
shopping page cart css chnages in popup
=>  css chnages

src/app/category/category.component.html
=> css chnages

src/app/door-configuration/door-configuration.component.html
=> css chnages latest pin

src/app/opener-selected/opener-selected.component.html
added button select another opener
=> added button select another opener

src/app/door-configuration/door-configuration.component.html, src/app/door-configuration/door-configuration.component.less, src/main.less
=> css changes in page

src/app/additional-options/additional-options.component.html
added residential flow additional options info popup's
=> added residential flow additional options info popup's

src/app/zip-results/zip-results.component.html
=> Removed close icon

src/app/category/category.component.html
=> added header class

src/app/home/home.component.html
css changes for camera selection div
=> css changes for camera selection div

src/app/additional-options/additional-options.component.html
added gdo and residential flow popup's
=> added gdo and residential flow popup's

src/app/collection/collection.component.html
=> css change

src/app/collection/collection.component.html
=> added info play classes

src/app/category/category.component.html, src/main.less
added css changes for garage door popup
=> added css changes

src/app/door-configuration/door-configuration.component.html
added gdo cart terms and total price popup
=> added gdo cart terms and total price popup

src/app/trending-now/trending-now.component.html, src/app/trending-now/trending-now.component.less
=> added coming soon

src/app/trending-now/trending-now.component.html, src/app/trending-now/trending-now.component.less, src/main.less, src/styles.css
=> class chnages

src/app/collection/collection.component.html, src/app/collection/collection.component.ts
toggle of play and gallery icons
=> toggle of play and gallery icons

src/app/trending-now/trending-now.component.html
=> header change

src/app/category/category.component.html
=> added header color

src/app/door-size/door-size.component.html, src/app/english.json
=> added step count to header

src/app/collection/collection.component.html
count to header has been added
=> count to header has been added

src/app/door-size/door-size.component.less
changed selected border color code
=> changed selected border color code

src/app/banner/banner.component.html, src/app/header/header.component.html
=> added few chnages

src/app/banner/banner.component.html, src/app/banner/banner.component.less, src/app/banner/banner.component.ts, src/app/collection/collection-data.ts, src/app/zip-results/zip-results.component.html, src/app/zip-results/zip-results.component.ts
=> fixed 4960 and few changes

src/app/gdo-config/gdo-config.component.html, src/app/gdo-door-size/gdo-door-size.component.html, src/app/nav/nav.component.html, src/app/shared/slider-component/slider-component.component.html, src/app/shared/slider-component/slider-component.component.less, src/app/shared/slider-component/slider-component.component.ts
=> slider iissue and css changes

src/app/additional-options/additional-options.component.html, src/app/banner/banner.component.html, src/app/banner/banner.component.less, src/app/banner/banner.component.ts, src/app/category/category.component.less, src/app/shopping-cart/shopping-cart.component.html
=> added few css changes

src/app/gdo-config/gdo-config.component.less, src/app/opener/opener.component.html
text changes in opener heading and font chnage in details near quantity
=> text changes in opener heading and font chnage in details near quantity

src/app/additional-options/additional-options.component.html, src/app/door-configuration/door-configuration.component.html
=> added miles popup changes

src/app/banner/banner.component.ts, src/main.less
media queries for and alert  4955 4958 4960
=> 4955 4958 4960

src/app/app.module.ts, src/app/customer-info/customer-info.component.html, src/app/customer-info/customer-info.component.spec.ts, src/app/customer-info/customer-info.component.ts, src/app/customer-service-info/customer-service-info.component.html, src/app/customer-service-info/customer-service-info.component.spec.ts, src/app/customer-service-info/customer-service-info.component.ts, src/app/routes.ts, src/app/shopping-cart/shopping-cart.component.html, src/app/shopping-cart/shopping-cart.component.ts
=> Checkout flow
